### PR TITLE
docs: Use relative link to other README files

### PR DESCRIPTION
**Pull request by hasecilu**
Current README on `develop` gives 404 error when clicking Spanish link.

### CODE REVIEW

**Comment by JYC333** [comment]
I think that because we are pointing to master branch README, and now Spanish README doesn't merge into master yet. Using relative link might be a better way.

And I also think put the README files in repo root is not so clean, maybe move other languages' README files into `.github`? See some repos doing like this. What's your thought @eliandoran?

**Comment by perfectra1n** [comment]
Another example of something similar - [Immich](https://github.com/immich-app/immich) uses a folder called `readme_i18n/` to hold the README.md files for other languages.

**Comment by hasecilu** [comment]
> Another example of something similar - [Immich](https://github.com/immich-app/immich) uses a folder called `readme_i18n/` to hold the README.md files for other languages.

lgtm

**Comment by eliandoran** [comment]
For now it's non-critical to move the README files somewhere else. We can do more cleaning-up after we implement the client-server architecture. Regardless, I prefer a dedicated directory like `readme_i18n/`. `.github` is reserved for CI and workflows, and READMEs are not GitHub-specific.

**Pull request merged**
