### PR TITLE
i18n: Continue Spanish translation, parts 3 and 4

### PR DESCRIPTION
**Pull request by hasecilu**
Some fixes were done thanks by using PO file with [Poedit](https://poedit.net/). It enhances a lot the workflow for translators. Previously using Neovim to translate was somewhat painful 🤪.

---

In order to easy the process to find the missing strings on alredy-translated JSON files I made a small script to create a `PO` file to translate it using Poedit, it tells you of minor issues like extra final point, case dfferences, etc.

The script could be the base for a sane workflow, maybe creating a `Makefile` or something like that.

Screenshot_2024-09-25_15-47-29

```shell
#!/usr/bin/env bash

# --------------------------------------------------------------------------------------------------
#
# Create a PO file to make easier the labor of translation
#
# Info:
# 	https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
# 	https://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/json2po.html
#
# Dependencies:
# 	jq
# 	translate-toolkit
# 		python-wcwidth
#
# Created by @hasecilu
#
# --------------------------------------------------------------------------------------------------

locales=(cn es ro)

# NOTE: Step 1
# Create PO files from English and localized JSON files as source
for locale in "${locales[@]}"; do
	json2po -t en "${locale}" "po-${locale}"
done

# NOTE: Step 2
# Make the translation

# NOTE: Step 3
# Update the localized JSON file with missing tags
# Needed to then replace with translated strings
for locale in "${locales[@]}"; do
	jq -s '.[0] * .[1]' en/translation.json "${locale}"/translation.json >merged.json
	mv merged.json "${locale}"/translation.json
done

# NOTE: Step 4
# Recover translation from PO files to JSON file
# Remember to set the indentation to 2 spaces
for locale in "${locales[@]}"; do
	po2json -t en "po-${locale}" "${locale}"
done

# NOTE: Step 5
# Remove PO files
for locale in "${locales[@]}"; do
	rm -r "po-${locale}"
done
```

### CODE REVIEW

**Review by JYC333 — APPROVED** [review]

**Review by eliandoran — APPROVED** [review]
Thank you for the contribution.

**Comment by eliandoran** [comment]
@hasecilu , when you have the time please also have a look at newest messages which were introduced. I think 141 translations are missing for Spanish at the moment, mostly for the keyboard actions.

**Comment by hasecilu** [comment]
> @hasecilu , when you have the time please also have a look at newest messages which were introduced. I think 141 translations are missing for Spanish at the moment, mostly for the keyboard actions.

Are from `server.json` file right?

**Comment by eliandoran** [comment]
> > @hasecilu , when you have the time please also have a look at newest messages which were introduced. I think 141 translations are missing for Spanish at the moment, mostly for the keyboard actions.
> 
> Are from `server.json` file right?

That would be correct, yes.

**Pull request merged**
