### PR TITLE
i18n support again (part 1)

### PR DESCRIPTION
**Pull request by Nriver**
I'll continue work on i18n here. As #257 was closed accidently.

### CODE REVIEW

**Comment by Nriver** [comment]
About 50% done. There is a dozen of file conflicts, I'd solve them now to aviod more conflicts later.

**Comment by eliandoran** [comment]
@Nriver , I think we should integrate the first batch of translations before we proceed any further.

**Comment by eliandoran** [comment]
@Nriver , I did the merge on my side since I was familiar with the changes that I did.

**Review by eliandoran — APPROVED** [review]
Looks really good so far, we can merge it as soon as the Chinese translations are updated.

**Comment by Nriver** [comment]
Ok, just updated the links in the Chinese translation file.

**Review by eliandoran — APPROVED** [review]
LGTM.

**Pull request merged**
