### PR TITLE
Remove hard-coded libraries part 2

### PR DESCRIPTION
**Pull request by JYC333**
Remove hard-coded libraries
- autocomplete
- codemirror

Code note for js frontend and backend couldn't show the code color, but other modes seem fine. Not sure whether it's acceptable changes. But codemirror is planned to upgrade to v6, probably fine for now. I can start look into upgrading codemirror right after this.

Related TriliumNext/trilium#5075

### CODE REVIEW

**Comment by eliandoran** [comment]
@JYC333 , for Code Mirror there is a chance that zadam patched something in it, we need to look for this.
I recommend trying to do a diff between what is now in `node_modules` and what we had in the `libraries`.
It would be important to have all the features in the past, and it might help us when we upgrade as well.

**Comment by JYC333** [comment]
@eliandoran zadam made some changes to `codemirro.js` and if replacing that js node cannot work. But the rest of codemirror components can be replaced with original files, the code color can be fixed easily.

I'll look into how to remove `codemirror.js` in another PR, because I think it could be a bit more work.

**Comment by eliandoran** [comment]
@JYC333, it appears that the syntax highlighting for JS notes has not been fixed yet. Can you confirm?

**Comment by JYC333** [comment]
It works from my side, force push again. This has rebased the PR #353 also. Could you take a look again?
image

**Review by eliandoran — APPROVED** [review]
LGTM.

**Pull request merged**
