### PR TITLE
Triggers full text search when Ctrl + Enter is pressed in note_autocomplete.

### PR DESCRIPTION
**Pull request by SiriusXT**
When searching for notes, title search sometimes fails to find the desired note.  

This PR enables full-text search directly by pressing Ctrl + Enter.

### CODE REVIEW

**Comment by eliandoran** [comment]
Hi, @SiriusXT .

Could you please provide a little bit more context about this PR?

1. Where exactly would a user benefit from this feature? For example, the Jump-to-note feature already has a full text search bound to Ctrl+Enter.
2. We most certainly need to find a way to inform the user about this feature, otherwise there will be no way to tell of its existence.

**Comment by SiriusXT** [comment]
1. I was also inspired by "Jump to Note," but when typing text into the input field and failing to find the desired note, pressing `Ctrl + Enter` does not trigger a jump to full-text search. Instead, it opens the "Create New Note" dialog. Currently, the only way to perform a full-text search is by either clicking the "Full-text Search" button with the mouse or moving the focus out of the input field.  

2. Primarily, in a new blank tab or the "Jump to Note" dialog, if the title search doesn't yield the desired note, we can use `Ctrl + Enter` to quickly jump to full-text search. This avoids the need to copy the search query, open the full-text search page, and paste the query again to perform the search.  

3. Of course, it is also acceptable to limit this feature to the input fields in new tabs and the "Jump to Note" dialog. Listening to all autocomplete input fields (including those in "Insert Note" or "Clone Note") won’t cause negative impact since the listener is only activated by `Ctrl + Enter`.  

4. The `search_placeholder` for the input field can be updated from "Search for a note by its name" to "Search for a note by its name, press `Ctrl + Enter` to jump to full-text search."

**Review by eliandoran — CHANGES_REQUESTED** [review]
What do you think instead of adding Ctrl+Enter for a full text search to have an entry underneath "Create and link child note 'foo'" that says "Search for 'foo'" (or similar)? I'm afraid altering the placeholder will turn the text longer and harder to interpret. And I don't think it will affect efficiency too much, since it will be <kbd>arrow down</kbd> + <kbd>enter</kbd> instead of <kbd>Ctrl</kbd> + <kbd>Enter</kbd>.

**Comment by SiriusXT** [comment]
Placing "Search for 'foo'" below "Create and link child note 'foo'" might confuse users who initially intend to search by name. Therefore, I placed "Search for 'foo'" at the end of the options, as users typically consider full-text search only when a name-based search yields no results. In this case, the "Search for 'foo'" entry appears as they scroll.

Additionally, allowing Ctrl+Enter to trigger the "Search for 'foo'" entry could be a solution, like this: 
图片
Of course, it is also fine not to listen for this shortcut key, just a minor suggestion.

**Comment by eliandoran** [comment]
@SiriusXT , looks perfect now. 

I was thinking as a future improvement to the search function, maybe we could add icons to the two special actions? Or even add icons of the notes.

**Review by eliandoran — APPROVED** [review]

**Pull request merged**
