### PR TITLE
Tweak menus

### PR DESCRIPTION
**Pull request by adoriandoran**
- Reordered and grouped the menu items to improve the user experience;
- Added missing icons;
- Improved the appearance of menus (added a shadow and reduced the contrast of separators);
- Added a fade animation when opening menus;
- Added a delay for opening submenus.

image

### CODE REVIEW

**Comment by SiriusXT** [comment]
I feel like almost every time I open the launcher menu, it's because I need to access the options. Wouldn't it be better to place the options at the top?

**Comment by adoriandoran** [comment]
> I feel like almost every time I open the launcher menu, it's because I need to access the options. Wouldn't it be better to place the options at the top?

I often open this menu primarily for the options as well. However, according to common design conventions, the options menu item is usually placed near the end of the menu. Here are some examples from the main menus of Firefox, Chrome, and Opera:

image

**Comment by SiriusXT** [comment]
It might be better to put options somewhere above Advanced, otherwise every time the mouse passes over Advanced it triggers the secondary menu.

**Comment by adoriandoran** [comment]
I think delaying the sub-menu would be better, as it would also benefit other menus. I'll look into it.

**Review by eliandoran — APPROVED** [review]
LGTM.

**Pull request merged**
