### PR TITLE
Change layout of promoted attributes

### PR DESCRIPTION
**Pull request by eliandoran**
This changes a bit the layout for promoted attributes, as follows:

1. The promoted attributes are now no longer part of the ribbon, but outside it, right after the title.
2. The promoted attributes will be shown in full and the user has to scroll past them.
3. The attributes are now shown one on each line instead of the traditional in-line presentation.
4. Clicking on the label will automatically focus the value input box.

This is a first step into making attributes looking more polished and inline with other editors (Notion, for example).

Before:

image

After:

image

### CODE REVIEW

**Comment by rom1dep** [comment]
I suppose this is completely out of scope for this PR (haven't tested it yet, tbh), but it would be nice to be able to render a group (tree/list) of notes having common attributes as a R/W grid, so said attributes could be read and written in bulk

**Comment by eliandoran** [comment]
To check spacing of check boxes as mentioned in https://github.com/TriliumNext/Notes/issues/546#issuecomment-2453546796 .

**Comment by eliandoran** [comment]
> I suppose this is completely out of scope for this PR (haven't tested it yet, tbh), but it would be nice to be able to render a group (tree/list) of notes having common attributes as a R/W grid, so said attributes could be read and written in bulk

@rom1dep , that would be quite a difficult task to handle, but I do plan to do it at some point. Will see how the project evolves.

**Comment by diyoyo** [comment]
Thanks for this!
I just tested it and it is way cleaner than before.
Only drawback: seems like it could at least be over 2 columns for very long lists. Something to be set in the settings?
at the end of the day, all this attribute stuff makes me think about [EspoCRM](https://www.espocrm.com/) in the way I use them. What I liked about it back in the days, was the Entity Layout Editor. Basically, it would mean that depending on the `~template` that one sets for a note, there would be a 'no code' config pane for the layout of the promoted attributes.

But yeah, this is the final trigger: tonight, I start digging into the code and see how I can contribute for real 😃

**Comment by Shmaur** [comment]
This is a good improvement, but there are some problems. For example, when there are many properties, it is necessary to slide a long time, only occupy a certain width, and the right side will appear very empty.
When editing notes, if you want to modify a property, you need to scroll all the way to the top.
And the property can not be hidden, can not be hidden will lead to occupy the general height of the screen, this experience is not very good.
I think the best way should provide user choice, you can keep the original interactive experience, you can hide, you can open and edit it directly whenever you need to edit it.
thank you

**Comment by Shmaur** [comment]
image
These properties take up more than half the height of my screen。I think this is a poor interactive experience

**Comment by diyoyo** [comment]
This really is a big problem now.

**Comment by eliandoran** [comment]
@diyoyo , do you have an example?

**Comment by eliandoran** [comment]
@Shmaur , I see most of your promoted attributes are not filled in.

Maybe we can change the promoted attributes mechanism to not show items that don't have a value yet, similar to how NextCloud Contact does it:

image

Moving the promoted attributes back to the ribbon is a no-go.

**Comment by Shmaur** [comment]
@eliandoran 
I'm sorry, maybe I didn't describe it correctly.

What I'm trying to say is that boosting stats takes up most of the content when there are too many of them. It is best to have the option of hiding all promoted properties and showing promoted properties.


When I have many promoted attributes, it will be very high, and one attribute occupies a row, it will make the content of the promoted attributes section very high, and it is impossible to distinguish between the promoted attributes section and the written content section.

I don't know if you understand the description.

Thank you for your reply.

**Comment by diyoyo** [comment]
I really like the idea of showing only the filled values, and that gives me another idea : when the field is 'multiple', it would be nice to collapse the list (since it's a no go to collapse the entire promoted section).
Exemple : when building a network of persons.
And since we are at it with the filled/unfilled, maybe we can then define a 'force-visible' in the label or relation definition.
To answer your question about an Exemple, it is the same as @Shmaur, my stuff looks the same. And as said in the discussion about latest release, the mobile version is making it even worse. Not because there is no scrollbar, but because we really need as much space as possible, even more looking at @Shmaur printscreen.
It still on my todo list to clone the repo and start playing with this. I thought I would have more time to dedicate on this. 
-------- Message d'origine --------Le 17/01/2025 15:00, Elian Doran - notifications at github.com  a écrit :
@Shmaur , I see most of your promoted attributes are not filled in.
Maybe we can change the promoted attributes mechanism to not show items that don't have a value yet, similar to how NextCloud Contact does it:
image.png (view on web)
Moving the promoted attributes back to the ribbon is a no-go.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/TriliumNext/Notes/pull/538#issuecomment-2598428709",
"url": "https://github.com/TriliumNext/Notes/pull/538#issuecomment-2598428709",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Shmaur** [comment]
before：Can be set to be visible and not take up too much content.

before

Current：Visibility cannot be set.
current

**Comment by eliandoran** [comment]
@Shmaur , just to clarify.

Promoted attributes are by definition, promoted, meaning that they are to be highlighted to the user.

Here's how Notion does it:

image

Here's how Obsidian does it:

image

There isn't much of a difference in how Trilium does it now. As far as I can see, neither Notion nor Obsidian has a way to collapse these attributes since the user can simply scroll past them if they are not wanted. If they are so problematic, then maybe they shouldn't be promoted attributes in the first place.

I will see about adding the possibility of collapsing empty attributes, but it will take to implement.

**Comment by Shmaur** [comment]
I think this implementation is not a good experience, too many "promoted properties" take up screen space, it is used infrequently, but it needs to be used occasionally. I need a visible button to toggle "Promote properties"

**Comment by eliandoran** [comment]
@Shmaur , contributions are welcome.

**Pull request merged**
