### PR TITLE
Conversion Validation

### PR DESCRIPTION
**Pull request by ProfDoof**
# Project Conversion Success Validation

We recently made some very large changes to the codebase and so I'm slowly going through and validating that any changes made to the codebase have not impacted the ability of the codebase to function. My first step to do so is to validate that all scripts run correctly. If they don't I will make a good faith attempt to repair the issue.

After that, I'm going to create builds for each of the supported platforms and request that any volunteers test that these builds run successfully on their machines and that we have an equivalently featured tool that has been converted to typescript.

## Script Validation
- [ ] start-server
- [ ] start-server-no-dir
- [ ] qstart-server
- [ ] start-electron
- [ ] start-electron-no-dir
- [ ] qstart-electron
- [ ] start-test-server
- [ ] switch-server
- [ ] switch-electron
- [ ] rebuild
- [ ] qswitch-server
- [ ] qswitch-electron
- [ ] build-backend-docs
- [ ] build-frontend-docs
- [ ] build-docs
- [x] webpack
- [ ] test-jasmine
- [x] test-es6
- [ ] test
- [x] postinstall

## Manual Build Validation

- [ ] Windows Desktop App
- [ ] Linux Desktop App
- [ ] MacOS Desktop App
- [ ] Android App
- [ ] iOS App? I don't know if we have this in existence already but I'm not sure that I personally am willing to pay the money necessary to make a production build of this
- [ ] Local Server Web App
- [ ] Remote Server Web App
- [ ] Docker Server Web App

# Follow-up Validation Needed?
## Scripted Validation? 
- [ ] Sync Server correctly syncing state
- [ ] Front-end Back-end Communication Robust to dropped connections
- [ ] Front-end Interface validation through tools like puppeteer, selenium, etc.
- [ ] Run all validation methods through Github Actions

### CODE REVIEW

**Comment by ProfDoof** [comment]
@zadam, sorry to ping you but I wanted to reach out and find out what prompted the choice to lock better-sqlite3 to node version 108.

**Comment by CobriMediaJulien** [comment]
i can help! :)

**Comment by ProfDoof** [comment]
@CobriMediaJulien, I can push up my most recent changes here in the next couple of days, feel free to poke around in that. (I did my yearly OS reset so everything is all over the place and everywhere except where it should be)

**Comment by CobriMediaJulien** [comment]
I can do that. If u want to can also write me some test cases. Or i just poke around.

**Comment by eliandoran** [comment]
@ProfDoof , any updates on this subject?

**Comment by ProfDoof** [comment]
So sorry, got busy with my PhD work. I'll try to get back to it but I'm not sure when. If others want to pick it up, feel free.

**Comment by eliandoran** [comment]
@ProfDoof , closing as out of date.

My suggestion would be, provided you have the time, to keep the checklist in this PR which is pretty good and see how the stable/beta/nightly version stands against it.

This thorough verification would have been great back in June when we did not have any public or internal releases, but it's never too late.

**Pull request closed without merging**
