### PR TITLE
Revisions number limit

### PR DESCRIPTION
**Pull request by SiriusXT**
Related to https://github.com/TriliumNext/Notes/issues/262
图片

### CODE REVIEW

**Review by JYC333 — COMMENTED** [review]
Thanks for this great work! I have one comment here.

image

I think it's good to add some notifications/information in this `Note revisions` modal to let user know what's the limit they have now. It's in `src/public/app/widgets/dialogs/revisions.js`. Not sure where could be the best place to add, maybe just right after the `Note revisions` title?

**Comment by SiriusXT** [comment]
How does this layout feel
图片

**Comment by JYC333** [comment]
Looks good! Just remind that, please don't put -1 for unlimit here, use something else :) Maybe an infinite symbol could be interesting, but just my thought, depends on how hard to implement. Using a word is also good enough!

**Comment by eliandoran** [comment]
> How does this layout feel 图片

Personally I wouldn't put it in the title bar since it complicates a bit the layout.

My recommendation would be to put it at the end of the dialog, either right underneath the list of revisions or at the bottom as a kind of a status bar.

Regardless, it shouldn't be as big as the title, as the size hierarchy is important and the limit of revisions is not as important as the title of the modal, so I would recommend making it default text size.

I would also rephrase the text slightly to something like "Maximum revisions per note: ". Love the Gear button, tho.

**Comment by SiriusXT** [comment]
Now：
图片

**Comment by eliandoran** [comment]
@SiriusXT , tested locally and works really good. I see you put it again in draft?

**Comment by SiriusXT** [comment]
Because a bug was found that for svg revisions, there were some problems with previewing in revisions, the last two commits fixed the problem. 

There is also a bug that is not related to this pr, for image/svg notes, by overwriting the image with another format, the original image becomes the revisions, but cannot be restored. May need to limit uploading images in different formats or find another way.

**Comment by eliandoran** [comment]
> Because a bug was found that for svg revisions, there were some problems with previewing in revisions, the last two commits fixed the problem.

Was this bug introduced by this PR or was it already present?

> There is also a bug that is not related to this pr, for image/svg notes, by overwriting the image with another format, the original image becomes the revisions, but cannot be restored. May need to limit uploading images in different formats or find another way.

Interesting, please don't forget to create an issue for it in order to track it.

**Comment by SiriusXT** [comment]
This bug has existed before, including in the zadam/trilium repository.

I will track the bug about different image format revisions in a separate issue later.

**Comment by SiriusXT** [comment]
> There is also a bug that is not related to this pr, for image/svg notes, by overwriting the image with another format, the original image becomes the revisions, but cannot be restored. May need to limit uploading images in different formats or find another way.

The bug has now been fixed by updating the note's type and MIME to match the revision's type and MIME when restoring the note.

**Comment by JYC333** [comment]
I found the ESC behaviour is bit wierd so I just make changes from my side, hope you don't mind.

Since we are using dropdown for revision list, then pressing ESC now will close the dropdown. I guess it's some side effect from upgrading Bootstrap. Now it should be fixed, and pressing ESC when the revision element is focused will close the dialog also.

I'm good with your other changes and great work!

**Comment by SiriusXT** [comment]
> I found the ESC behaviour is bit wierd so I just make changes from my side, hope you don't mind.
> 
> Since we are using dropdown for revision list, then pressing ESC now will close the dropdown. I guess it's some side effect from upgrading Bootstrap. Now it should be fixed, and pressing ESC when the revision element is focused will close the dialog also.
> 
> I'm good with your other changes and great work!

Great. I also encountered the revised left column suddenly disappearing before. I always thought there was something wrong with its layout.

**Comment by JYC333** [comment]
I found this when I upgraded Bootstrap. Using dropdown probably not the best choice, but I think I will leave it for now since it's working fine :)

**Review by JYC333 — APPROVED** [review]

**Review by eliandoran — APPROVED** [review]
LGTM.

**Pull request merged**
