### PR TITLE
Use matrix strategy for CI/CD

### PR DESCRIPTION
**Pull request by perfectra1n**
- Use matrix strategy for CI/CD
- Fix the start-docker.sh file to use sh instead of bash because Alpine doesn’t have bash.
- Docker health checks in CI/CD for both Dockerfiles
- Remove Alpine-specific Action YAML

Run:
https://github.com/perfectra1n/Notes/actions/runs/10757405589

[GHCR](https://github.com/perfectra1n/Notes/pkgs/container/notes):
image
image

[DockerHub](https://hub.docker.com/repository/docker/perfectra1n/notes/tags):
image

### CODE REVIEW

**Comment by perfectra1n** [comment]
Getting attestations to work is also going to be...extremely difficult with this setup. If you think they're highly needed, I can keep working away at it. I'm definitely going to need a couple days away from this now that it's working LOL

**Comment by JYC333** [comment]
Great work! Have some questions:

1. There is an unknow arch in ghcr, do you know where it comes from?
2. Does test build need to test in different platforms? Not sure is that needed.
3. I see in DockerHub triliumnext/notes has many tags with hash tag, do we need those tags? My feeling is we only need version tag and nightly build tag in DockerHub.

**Comment by perfectra1n** [comment]
1. Well I've gotta say I don't think I've ever seen this before:

```
docker pull ghcr.io/perfectra1n/notes:sha256-416ebcdb1430f74701a0af8eed77b0027254d976@sha256:82baed2479e317919dd76e05374b8988bb82012fe490d8b8d9287adfea97b1da
ghcr.io/perfectra1n/notes@sha256:82baed2479e317919dd76e05374b8988bb82012fe490d8b8d9287adfea97b1da: Pulling from perfectra1n/notes
unsupported media type application/vnd.in-toto+json
```

I'll remove that strange digest from the build, I believe it's the attestation from the previous steps.

2. Currently we're not testing the different architectures, we're testing the two different Dockerfiles. We've already run into issues with the discrepancies between the two different Dockerfiles that we're building. #400 
3. That was there previously to me making these changes, where the associated SHA of the latest commit is added as a valid tag. #327 from you is still open, so I'm not sure if it's been confirmed that we want to change tags? I'm fine with doing so, if we want to.

**Comment by JYC333** [comment]
> 3\. That was there previously to me making these changes, where the associated SHA of the latest commit is added as a valid tag. [Create nightly release action #327](https://github.com/TriliumNext/Notes/pull/327) from you is still open, so I'm not sure if it's been confirmed that we want to change the tags to what you described? I'm fine with doing so, if we want to.

From my experience, having SHA as tag for image is quite useless, it's too troublesome for users to pull the image to based on the SHA tag and I haven't done this before. The other reason could be, for example, the image below shows the digest for `v0.90.6-beta` and `sha-4106cc6` are the same. I guess the digest for tag `sha-4106cc6` barely gonna be used. And it'll be much cleaner if we only have version tags on DockerHub, will also let people who checks triliumnext DockerHub feel that we are not too casual.
image

For the nightly release, we can have that after we merge #327. We can overwrite the digest under nightly tag.

And I also find that you are still pushing images to triliumnext/notes, not sure whether you are aware of that. We already have 10 pages of images/tags, but we only have 6 releases now, it's not very reasonable for me. And I think we don't need `develop` tag, `nightly` could be a good one after #327 is merged. It can update daily instead of pushing based on commits.
image

**Comment by perfectra1n** [comment]
@eliandoran are you okay with removing the `sha*` tags that currently exist? I think that it would be nice to have the `develop` tag with the latest commit, while the `nightly` tag would be reserved for the container built at the end of the day, but I don't care too much either way...

> And I also find that you are still pushing images to triliumnext/notes, not sure whether you are aware of that. 

That's because the CI/CD that pushes to DockerHub is using my API key to push to the DockerHub organization, it's not *me* per-se, it's just my API key. Any development that I'm doing is being pushed to my fork.

What you've brought up is outside of the scope for this PR, however. This PR is just to use the matrix strategy. I think it would be better if another PR was opened (or previous merged/closed) that include the suggestions you bring up above.

**Comment by JYC333** [comment]
I agree I'm a bit overthinking and increasing the scope of this PR. Create an issue to follow up this #412.

Otherwise, the changes look good to me.

**Review by JYC333 — APPROVED** [review]

**Comment by eliandoran** [comment]
> @eliandoran are you okay with removing the `sha*` tags that currently exist? I think that it would be nice to have the `develop` tag with the latest commit, while the `nightly` tag would be reserved for the container built at the end of the day, but I don't care too much either way...
> 

I think it would be nice to get rid of the SHA labels, yes. Of course , in a separate PR. 

> 
> > And I also find that you are still pushing images to triliumnext/notes, not sure whether you are aware of that. 
> 
> 
> That's because the CI/CD that pushes to DockerHub is using my API key to push to the DockerHub organization, it's not *me* per-se, it's just my API key. Any development that I'm doing is being pushed to my fork.
> 

Is there a way to make it appear as if the org is pushing it instead of a particular person? I think that would make it seem more professional. I've done a similar change in the GitHub release process, since we are now releasing directly via GitHub Actions.

**Comment by perfectra1n** [comment]
Yeah it looks like the "org" can't:
image
image


But we could create a user with a more professional name if you would like :)

**Comment by perfectra1n** [comment]
> I've done a similar change in the GitHub release process, since we are now releasing directly via GitHub Actions.

Oh, hopefully I haven't created a conflict then with my changes 😬

**Review by eliandoran — APPROVED** [review]

**Pull request merged**
