### PR TITLE
Update Node.js version

### LINKED ISSUE #223: Update Node.js version
The project is currently Node 18-compliant.

The newer LTS would be 20.9.0: https://nodejs.org/en/blog/release/v20.9.0, so it might be worth bumping the version.

### LINKED ISSUE #5071: Update tooling dependencies
```
Package                     Current    Wanted    Latest  Location                              Depended by
rimraf                        5.0.5     5.0.5     6.0.1  node_modules/rimraf                   TriliumNext
webpack                      5.90.3    5.90.3    5.93.0  node_modules/webpack                  TriliumNext
nodemon                       3.1.0     3.1.0     3.1.4  node_modules/nodemon                  TriliumNext
jsdoc                         4.0.2     4.0.2     4.0.3  node_modules/jsdoc                    TriliumNext
```

### LINKED ISSUE #5074: Update Node.js version
The project is currently Node 18-compliant.

The newer LTS would be 20.9.0: https://nodejs.org/en/blog/release/v20.9.0, so it might be worth bumping the version.

### PR DESCRIPTION
**Pull request by eliandoran**
Closes TriliumNext/trilium#5074 .

1. The change to Node 20 does not seem to cause any issues with the code base, being an LTS update.
1. Updated `better-sqlite3` from 8.4.0 to 8.5.0 because it contains prebuilt binaries for Electron v25. This should make `npm run switch-electron` run faster and not require additional tools on some operating systems.

### CODE REVIEW

**Comment by eliandoran** [comment]
@TriliumNext/development , I would appreciate a local test of this PR.
You need to make sure `node --version` is OK for you.
Test `npm run start-server`, but also `npm run switch-electron` followed by `npm run start-electron` (don't forget to switch back to server with `npm run switch-server`).

**Comment by alexpietsch** [comment]
@eliandoran I tested it on my Windows PC: I made a fresh clone of the repo, ran `npm i`, and then `npm run start-server`.
I chose "I am a new user" and could set up. After logging in, I see a lot of `Error: Cannot set headers after they are sent to the client` errors. The reason is `Error: EPERM: operation not permitted, rename 'B:\Notes\data\sessions\brERX1URXz1lNi77UEO9Nnq1rj79Dt3H.json.4212621842' -> 'B:\Notes\data\sessions\brERX1URXz1lNi77UEO9Nnq1rj79Dt3H.json']`

I did the same for electron, and after running `npm run start-electron` I only get an error 
```
Error: The module '\\?\B:\Notes\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
```

But I was able to start electron and use it perfectly fine by first starting the server, completing the setup, stopping the server, then running `npm run switch-electron` followed by `npm run start-electron`.
I also tried to clone the repo, installing dependencies, running `npm run switch-electron` followed by `npm run start-electron`, but had no success.

**Comment by eliandoran** [comment]
@alexpietsch , can you confirm your Node version using `node --version`?

And also, what is the output of `npm run switch-electron`?

**Comment by eliandoran** [comment]
@alexpietsch ,

For the Electron build, try this in a Git Bash:

```sh
git fetch
git checkout origin/feature/update_to_node20
rm -r data node_modules
npm i
npm run switch-electron
npm run start-electron
```

For me it started just fine.

**Comment by alexpietsch** [comment]
> @alexpietsch , can you confirm your Node version using `node --version`?

Output: `v20.15.1`


> And also, what is the output of `npm run switch-electron`?

This script does not work on windows (because `rm` is not recognized). I did the steps manually (deleting ./node_modules/better-sqlite3, then running `npm install`)

I followed your steps (with GitBash) and it worked!
But we should take a look if we want to support windows.

**Comment by eliandoran** [comment]
@alexpietsch , I've just pushed a change regarding `rm -rf`, using `rimraf` should make it cross-platform.
Let me know if you have any other issues.

Regarding

```
[Error: EPERM: operation not permitted, rename 'C:\Users\Elian\Projects\TriliumNext\data\sessions\WMCk1bAlG6HCBjNajFh-NPcVNZlF1dKn.json.1509196086' -> 'C:\Users\Elian\Projects\TriliumNext\data\sessions\WMCk1bAlG6HCBjNajFh-NPcVNZlF1dKn.json'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\Elian\\Projects\\TriliumNext\\data\\sessions\\WMCk1bAlG6HCBjNajFh-NPcVNZlF1dKn.json.1509196086',
  dest: 'C:\\Users\\Elian\\Projects\\TriliumNext\\data\\sessions\\WMCk1bAlG6HCBjNajFh-NPcVNZlF1dKn.json'
}
```

That one is caused by an upstream dependency, I'll create a separate ticket for it.

Let me know if the PR is OK so I can merge it for the upcoming release (soon!).

**Pull request merged**
