### PR TITLE
Classic editor for text notes (with fixed toolbar)

### PR DESCRIPTION
**Pull request by eliandoran**
Added an option in Text Notes -> Formatting toolbar to allow switching between a floating editor (the current implementation) and a fixed toolbar.

image

Floating editor:

image

Fixed editor:

image

### CODE REVIEW

**Review by adoriandoran — APPROVED** [review]

**Comment by Br0kenSilos** [comment]
I like it.  :-)

**Comment by Praetorian1410** [comment]
Thank you so much - exactly what I was after!

**Comment by ups7** [comment]
I really wanted the fixed toolbar, thank you!

**Comment by brokoler** [comment]
This feature is great, thanks a lot!

There is one important icon missing, that I expected would be added.
The "Find and Replace" icon is missing in the fixed toolbar in TriliumNext.
In CKEditor it's part of the toolbar and was also part of Trilum: https://github.com/zadam/trilium/issues/679

276420927-686c56e2-bf5d-4e75-ad6f-9598e442f38a

Not sure if I'm missing something, but it would be great if the "Find and Replace" icon could be added as well to the fixed toolbar.

**Comment by eliandoran** [comment]
@brokoler , thanks for the report. Added it.

**Pull request merged**
