### PR TITLE
client: Added scroll to bottom button

### PR DESCRIPTION
**Pull request by rainrisa**
### Description

This pull request adds a scroll-to-bottom button to enhance navigation within notes, allowing users to easily scroll to the bottom of a note for editing or adding additional text.

### Screenshot

Scroll to Bottom Button

### Notes

This is my first contribution to the project, so I appreciate your feedback and any suggestions for improvement. Thank you!

### CODE REVIEW

**Comment by SiriusXT** [comment]
It doesn't work properly when multiple tabs are opened, and it doesn't work properly in a split window.
I feel that there are many pitfalls in getting the scrolling container through `const $scrollingContainer = $('.scrolling-container');`
However, it may be difficult to have a good method suitable for integration into the main code to accurately obtain the scrolling-container.

**Comment by rainrisa** [comment]
Thanks for the feedback. I’ve pushed a fixed version that addresses the issues mentioned. Let me know if there are any other thoughts. Appreciate the guidance

**Comment by rainrisa** [comment]
trilium-scroll-to-top-and-bottom

I have developed an improved version that includes buttons for scrolling to both the top and bottom of the notes.

I welcome any feedback and guidance you may have

**Comment by perfectra1n** [comment]
This looks great, thanks for putting this together!

**Comment by SiriusXT** [comment]
When scrolling to the bottom using the scrollbar or mouse wheel, the scroll button doesn't change to the upward scroll icon. 
The scroll button only changes when clicked, not dynamically. 
I think this might be achievable by listening to the scroll event, but since listening to scroll events can be CPU-intensive, it would be better to offer this functionality as a plugin for those who need it.

**Comment by eliandoran** [comment]
@rainrisa , your work is appreciated but I think in its current form it would most likely be better to have it as a dedicated widget that can be easily plugged into the application, rather than part of the application itself.

If you wish to proceed to have this in the application, we would have to implement it as a floating button that appears in the bottom-right as @SiriusXT mentioned.

I'm going to put in draft for now, but let me know how you wish to proceed.

**Comment by eliandoran** [comment]
Closing for now, although I would love to have a scroll to top function implemented provided it respects @SiriusXT 's suggestion.

The scroll to top would be particularly useful due to the changes we've made to the promoted attributes, which are now part of the scrollable area, at the top. If the user is at the bottom they might want to access that section rapidly (especially since we might add even more things to the top of the note at some point).

A scroll to bottom would not be as useful in my opinion, since it has no immediate user-actionable items like the header. For power users, pressing Ctrl+Home and Ctrl+End to reach the top and bottom should not be problematic.

**Pull request closed without merging**
